spring.application.name=CoreGS

# Contexto de la aplicacion
server.servlet.context-path=/coreGS

# Base de datos
##spring.datasource.url=jdbc:mysql://host.docker.internal:3306/coregs?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://demobd.cbui2sso4h2h.us-east-2.rds.amazonaws.com:3306/coregs?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Septiembre15
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# SQL
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.orm.jdbc.extract=OFF


# Tiempo minimo para registrar una consulta lenta
coregs.database.slow-query-threshold-ms=500

# Configuraciones de Jwt Service
jwt.secret=esta-es-una-clave-secreta-muy-larga-para-jwt-123456

# Tiempo de Access Token: 15 minutos
jwt.expiration=900000

# Tiempo de Refresh Token: 7 dias
jwt.refresh-expiration=604800000

# Activacion de dispositivo
dispositivo.activacion.expiracion-minutos=15
dispositivo.activacion.url=http://192.168.1.75:3000/authentication/activar-dispositivo

# Configuracion de formato de Logs
#logging.file.path=C:/logs/coregs
#logging.file.name=${logging.file.path}/coregs.log
logging.log.max-history=30
logging.log.max-file-size=50MB
logging.log.total-size-cap=2GB

logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR

# Correo
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# OpenAPI / Swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false